name: Code checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches:  [ main ]

jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - user: actions/checkout@v2
      - name: Install python
        user: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install -upgrade pip
          pip install -r requirements.txt
      - name: Run flake8
        run: flake8 .
      - name: Run mpyp
        run: mypy .
